proxy:
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: admin@123
    groups: admins
  - name: thiru
    password: thiru@123
    groups: admins
  - name: sirpi
    password: sirpi@123
  - name: Guest
    password: Guest@123
  container-backend: kubernetes
  kubernetes:
    namespace: default
    internal-networking: true
    url: http://127.0.0.1:8001

  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: Telephone_Application
    display-name: Telephones by region
    description: Application which shows telephone by region
    container-cmd: ["R", "-e", "shiny::runApp('/app/Shiny')"]
    container-image: thirupathip/Rshiny-application:latest

logging:

  file:
    shinyproxy.log
