proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: admin@123
    groups: admins
  - name: thiru
    password: thiru@123
    groups: admins
  - name: sirpi
    password: sirpi@123
  - name: Guest
    password: Guest@123
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    image-pull-policy: IfNotPresent
    image-pull-secret: ${SecretForDockerRegistry} 
  specs:
  - id: Telephone_Application
    display-name: Test by region
    description: Application which shows test by region
    container-cmd: ["R", "-e", "shiny::runApp('/app/Shiny')"]
    container-image: thirupathip/Rshiny-application:latest

logging:
  file:
    shinyproxy.log
